### ISSUE TITLE
Upgrade net7.0 the BlazorApp crashed,but net 6.0 is fine!

### ISSUE THREAD

**Issue by pccai** [egvijayanand/WeeklyXamarinBlazor#21]
android sdk also to 31.

**Comment by egvijayanand** [comment]
Have upgraded the entire solution to target .NET 7.

To be specific, **.NET MAUI on .NET 7 works with Android SDK API level 33**. Whereas on .NET 6, it works with API level 31.

For this reason, have specifically included a global.json in the root of the repository and updated the AndroidManifest.xml file as well to point to .NET 7 and API level 33 respectively.

Ensure you're on the latest version, if not pull the changes from the main branch.

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
If you want to still work on .NET 6, get the source from this tagged version.

https://github.com/egvijayanand/WeeklyXamarinBlazor/releases/tag/sr6-version
